"""Plot evaluation metrics for the medrag-cdv poster.

Reads `results/metrics.csv` (generated by `src.evaluation --by-qtype`)
and writes PNG figures to `results/plots/`:

- `overall.png` — main bar chart, 3 metrics × 4 retrievers
- `recall_per_qtype.png`, `mrr_per_qtype.png`, `rouge_per_qtype.png`,
  `abstention_per_qtype.png` — same 4 retrievers, stratified by qtype
  (only qtypes with n >= --min-n shown)
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

DEFAULT_METRICS_PATH = Path("results/metrics.csv")
DEFAULT_OUTPUT_DIR = Path("results/plots")

# Display order, colours, and labels for retrievers.
RETRIEVER_ORDER = ["none", "bm25", "dense", "entity"]
RETRIEVER_LABELS = {
    "none": "LLM-only",
    "bm25": "BM25",
    "dense": "Dense",
    "entity": "Entity-Aware",
}
RETRIEVER_COLORS = {
    "none": "#888888",
    "bm25": "#1f77b4",
    "dense": "#ff7f0e",
    "entity": "#2ca02c",
}


def read_metrics(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _grouped_bar(
    ax: plt.Axes,
    x_labels: list[str],
    series_by_retriever: dict[str, list[float]],
) -> None:
    """Plot grouped bars: one group per x_label, one bar per retriever."""
    width = 0.2
    n_retrievers = len(RETRIEVER_ORDER)
    x = np.arange(len(x_labels))
    for i, retriever in enumerate(RETRIEVER_ORDER):
        if retriever not in series_by_retriever:
            continue
        values = series_by_retriever[retriever]
        offset = (i - n_retrievers / 2 + 0.5) * width
        ax.bar(
            x + offset,
            values,
            width,
            label=RETRIEVER_LABELS[retriever],
            color=RETRIEVER_COLORS[retriever],
        )
    ax.set_xticks(x)
    ax.set_xticklabels(x_labels, rotation=30, ha="right")
    ax.grid(True, axis="y", alpha=0.3)
    ax.set_axisbelow(True)


def plot_overall(metrics: list[dict], output: Path) -> None:
    """Main bar chart: Recall@3 / MRR / ROUGE-L for the 4 retrievers."""
    overall_by_retriever = {
        r["retriever"]: r for r in metrics if r["qtype"] == "all"
    }
    metric_keys = ["recall_at_k", "mrr", "rouge_l_f1"]
    metric_labels = ["Recall@3", "MRR", "ROUGE-L F1"]

    series = {
        retriever: [float(overall_by_retriever[retriever][k]) for k in metric_keys]
        for retriever in RETRIEVER_ORDER
        if retriever in overall_by_retriever
    }

    n = overall_by_retriever.get("dense", {}).get("n", "?")
    fig, ax = plt.subplots(figsize=(9, 5))
    _grouped_bar(ax, metric_labels, series)
    ax.set_ylabel("Score")
    ax.set_title(f"Overall evaluation metrics (n={n} questions)")
    ax.legend(loc="upper right")
    plt.tight_layout()
    plt.savefig(output, dpi=150)
    plt.close(fig)
    print(f"  wrote {output}")


def plot_stratified(
    metrics: list[dict],
    metric_key: str,
    metric_label: str,
    output: Path,
    min_n: int,
) -> None:
    """One stratified bar chart for a single metric, qtypes on x-axis."""
    stratified = [
        r
        for r in metrics
        if r["qtype"] != "all" and int(r["n"]) >= min_n
    ]
    if not stratified:
        print(f"  skipped {output.name}: no qtypes with n >= {min_n}")
        return

    qtypes = sorted(
        {r["qtype"] for r in stratified},
        key=lambda qt: -max(int(r["n"]) for r in stratified if r["qtype"] == qt),
    )
    n_per_qtype = {
        qt: max(int(r["n"]) for r in stratified if r["qtype"] == qt)
        for qt in qtypes
    }

    series: dict[str, list[float]] = {}
    for retriever in RETRIEVER_ORDER:
        series[retriever] = []
        for qt in qtypes:
            match = [
                r
                for r in stratified
                if r["retriever"] == retriever and r["qtype"] == qt
            ]
            series[retriever].append(float(match[0][metric_key]) if match else 0.0)

    x_labels = [f"{qt}\n(n={n_per_qtype[qt]})" for qt in qtypes]
    fig, ax = plt.subplots(figsize=(max(10, len(qtypes) * 1.5), 5))
    _grouped_bar(ax, x_labels, series)
    ax.set_ylabel(metric_label)
    ax.set_title(f"{metric_label} per qtype (qtypes with n ≥ {min_n})")
    ax.legend(loc="upper right")
    plt.tight_layout()
    plt.savefig(output, dpi=150)
    plt.close(fig)
    print(f"  wrote {output}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--metrics", type=Path, default=DEFAULT_METRICS_PATH,
        help="Path to the metrics CSV (generated by src.evaluation --by-qtype)",
    )
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT_DIR,
        help="Directory to write PNGs into.",
    )
    parser.add_argument(
        "--min-n", type=int, default=10,
        help="Minimum sample size to include a qtype in stratified plots.",
    )
    args = parser.parse_args()

    args.output.mkdir(parents=True, exist_ok=True)
    metrics = read_metrics(args.metrics)
    print(f"Loaded {len(metrics)} metric rows from {args.metrics}")

    plot_overall(metrics, args.output / "overall.png")
    plot_stratified(
        metrics, "recall_at_k", "Recall@3",
        args.output / "recall_per_qtype.png", args.min_n,
    )
    plot_stratified(
        metrics, "mrr", "MRR",
        args.output / "mrr_per_qtype.png", args.min_n,
    )
    plot_stratified(
        metrics, "rouge_l_f1", "ROUGE-L F1",
        args.output / "rouge_per_qtype.png", args.min_n,
    )
    plot_stratified(
        metrics, "abstention_rate", "Abstention rate",
        args.output / "abstention_per_qtype.png", args.min_n,
    )


if __name__ == "__main__":
    main()
